"""new fields in User Model

Revision ID: 1472a69cae19
Revises: 3ffe7c6e70c7
Create Date: 2020-09-09 19:20:34.443987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1472a69cae19'
down_revision = '3ffe7c6e70c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
