"""'followers'

Revision ID: 544257f0e775
Revises: 1472a69cae19
Create Date: 2020-09-10 22:11:26.627110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544257f0e775'
down_revision = '1472a69cae19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
